services:
  app:
    build: .
    container_name: chatting-embedding
    env_file: .env
    ports:
      - "5001:5001"
    restart: unless-stopped
    networks:
      - n8n-network

networks:
  n8n-network:
    external: true

