name: Build and Deploy Docker image to Server (Password SSH)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .env file for Docker build
        run: |
          echo "ES_HOST=${{ secrets.ES_HOST }}" > .env
          echo "ES_USER=${{ secrets.ES_USER }}" >> .env
          echo "ES_PASSWORD=${{ secrets.ES_PASSWORD }}" >> .env
          echo "TELEGRAM_CHATS_INDEX_NAME=${{ secrets.TELEGRAM_CHATS_INDEX_NAME }}" >> .env
          echo "SEED_INDEX_NAME=${{ secrets.SEED_INDEX_NAME }}" >> .env
          echo "PYTHONUNBUFFERED=1" >> .env

      - name: Build Docker image
        run: docker build -t chatting-embedding:latest .

      - name: Save Docker image as tar
        run: docker save chatting-embedding:latest -o chatting_embedding.tar

      - name: Fix permissions
        run: chmod 644 chatting_embedding.tar

      - name: Copy image to server (password auth)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "chatting_embedding.tar"
          target: "~/chatting-embedding/"

      # 서버에 배포 및 실행 스텝
      - name: Deploy on server (load & run, password auth)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            docker load -i ~/chatting-embedding/chatting_embedding.tar
            docker stop chatting-embedding || true
            docker rm chatting-embedding || true
            docker image prune -f
            docker run -d \
              --name chatting-embedding \
              --network n8n-network \
              -p 5001:5001 \
              --restart unless-stopped \
              -e TZ=Asia/Seoul \
              chatting-embedding:latest
            rm -rf ~/chatting-embedding

